# Generated by Django 3.2 on 2021-05-13 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, help_text='Name of the commentator.', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email of the commentator.', max_length=254)),
                ('description', models.TextField(help_text='Comment Description.', verbose_name='Comment Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created Date Time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated Date Time')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent of this comment. If none, this is the Parent comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='blog.comment', verbose_name='Parent Comment')),
                ('post', models.ForeignKey(help_text='Related post of this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentators', to=settings.AUTH_USER_MODEL, verbose_name='Commentator')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-id'],
            },
        ),
    ]
